[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
build_info = false
extra_output = ["storageLayout"]

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000 }

# Hedera Testnet Configuration
[rpc_endpoints]
hedera_testnet = "https://testnet.hashio.io/api"
hedera_mainnet = "https://mainnet.hashio.io/api"

[etherscan]
hedera_testnet = { key = "${HEDERA_API_KEY}" }

# Gas settings optimized for Hedera
[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = "dhfoDgvulfnTUtnIf"
